raspi-gpio set 2 op dl
raspi-gpio set 2 op dh
raspi-gpio set 2 op dl
raspi-gpio set 2 op dh
raspi-gpio set 2 op dl
raspi-gpio set 2 op dh
raspi-gpio set 2 op dl
raspi-gpio set 2 op dh
raspi-gpio set 2 op dl
raspi-gpio set 2 op dh
raspi-gpio set 2 op dl
raspi-gpio set 2 op dh
raspi-gpio set 2 op dl
raspi-gpio set 2 op dh
