<!DOCTYPE html>
<html>
<body>

<p>A paragraph generated by html.</p>

<?php
$x = "<p>A paragraph generated within php using a variable and the echo command.</p>";
echo "$x";
?>

<?php
$y = "<p>A paragraph generated within php using a variable and the print command.</p>";
print($y);
?>

<?php
	include 'SubList.php'
?>

</body>
</html>
