<!DOCTYPE html>
<html>
<body>

<p>A message generated by html.</p>

<?php
$x = "A message generated within php using a variable and the echo command.";
echo "$x";
$y = "Hello from a print command";
print($y);
?>

<ul>
	<li>Go to <a href="http://www.dramaturgist.com">SAGA Website</a>.</li>
	<li>Go to <a href="https://www.opensourceinstruments.com">OSI Website</a>.</li>
</ul>

</body>
</html>
